import turtle
tom = turtle. Turtle()
tom.pencolor('blue')
tom.pensize(3)
tom.penup()
tom.goto(0,-300)
tom.pendown()
tom.circle(100)
tom.penup()
tom.goto(0,-100)
tom.pendown()
tom.circle(70)
tom.penup()
tom.goto(0,40)
tom.pendown()
tom.circle(40)
tom.penup()
tom.goto(0,40)
tom.pendown()
