import turtle
tom = turtle.Turtle()
sam = turtle.Turtle()
tom.shape('turtle')
sam.shape('turtle')
tom.color('blue')
sam.color('red')
tom.penup()
sam.penup()
tom.goto(0,200)
sam.goto(0,-200)
tom.pendown()
tom.pensize(5)
tom.circle(100)
sam.right(90)
sam.write('1 done, 4 to go!')
tom.right(72)
tom.circle(100)
sam.forward(10)
sam.write('2 done, 3 to go!')
tom.right(72)
tom.circle(100)
sam.forward(10)
sam.write('3 done, 2 to go!')
tom.right(72)
tom.circle(100)
sam.forward(10)
sam.write('4 done, 1 to go!')
tom.right(72)
tom.circle(100)
sam.forward(10)
sam.write('5 done, 0 to go!')
sam.forward(20)
sam.write('good job tom!')
tom.penup()
tom.forward(75)
tom.hideturtle()
tom.write('thanks')
