##import turtle
##screen = turtle.Screen() # create a Screen object
##screen.setup(600,600) # big square screen
##screen.bgcolor('red') # background colour
##jaymit = turtle.Turtle()
##jaymit.forward(300)
##screen.bgcolor('orange')
##jaymit.left(180)
##jaymit.forward(600)
##jaymit.reset()# when jaymit hits the wall
##screen.bgcolor('yellow') # the background colour changes
##jaymit.left(180)
##jaymit.forward(600)
##jaymit.reset()# when jaymit hits the wall
##screen.bgcolor('blue') # the background colour changes
##jaymit.left(180)
##jaymit.forward(600)
##jaymit.reset()# when jaymit hits the wall
##screen.bgcolor('yellow') # the background colour changes
##jaymit.left(180)
##jaymit.forward(600)
##jaymit.reset()# when jaymit hits the wall
##screen.bgcolor('blue') # the background colour changes

#PinWheel

##import turtle
##tom=turtle.Turtle()
##tom.pencolor('black')
##tom.pensize(5)
##tom.fillcolor('red')
##tom.begin_fill()
##tom.circle(50)
##tom.end_fill()
##tom.left(60)
##tom.fillcolor('orange')
##tom.begin_fill()
##tom.circle(50)
##tom.end_fill()
##tom.left(60)
##tom.fillcolor('yellow')
##tom.begin_fill()
##tom.circle(50)
##tom.end_fill()
##tom.left(60)
##tom.fillcolor('green')
##tom.begin_fill()
##tom.circle(50)
##tom.end_fill()
##tom.left(60)
##tom.fillcolor('blue')
##tom.begin_fill()
##tom.circle(50)
##tom.end_fill()
##tom.left(60)
##tom.fillcolor('purple')
##tom.begin_fill()
##tom.circle(50)
##tom.end_fill()
##tom.left(60)

#SnowFlake

import turtle
tom=turtle.Turtle()
tom.pensize(3)
tom.pencolor('blue')
tom.forward(100)
tom.backward(20)
tom.right(60)
tom.forward(20)
tom.backward(20)
tom.left(120)
tom.forward(20)
tom.backward(20)
tom.right(60)
tom.backward(80)
tom.right(60)
tom.forward(100)
tom.backward(20)
tom.right(60)
tom.forward(20)
tom.backward(20)
tom.left(120)
tom.forward(20)
tom.backward(20)
tom.right(60)
tom.backward(80)
tom.right(60)
tom.forward(100)
tom.backward(20)
tom.right(60)
tom.forward(20)
tom.backward(20)
tom.left(120)
tom.forward(20)
tom.backward(20)
tom.right(60)
tom.backward(80)
tom.right(60)
tom.forward(100)
tom.backward(20)
tom.right(60)
tom.forward(20)
tom.backward(20)
tom.left(120)
tom.forward(20)
tom.backward(20)
tom.right(60)
tom.backward(80)
tom.right(60)
tom.forward(100)
tom.backward(20)
tom.right(60)
tom.forward(20)
tom.backward(20)
tom.left(120)
tom.forward(20)
tom.backward(20)
tom.right(60)
tom.backward(80)
tom.right(60)
tom.forward(100)
tom.backward(20)
tom.right(60)
tom.forward(20)
tom.backward(20)
tom.left(120)
tom.forward(20)
tom.backward(20)
tom.right(60)
tom.backward(80)
tom.right(60)

##silly walks

##import turtle
##tom=turtle.Turtle()
##sam=turtle.Turtle()
##sam.penup()
##sam.goto(-200,200)
##tom.penup()
##tom.goto(-200,-200)
##tom.pendown()
##sam.pendown()
##sam.color( 'blue')
##sam.forward(50)
##sam.left(90)
##sam.forward(20)
##sam.right(90)
##sam.forward(50)
##sam.right(90)
##sam.forward(20)
##sam.left(90)
##sam.forward(50)
##sam.left(90)
##sam.forward(20)
##sam.right(90)
##sam.forward(50)
##sam.right(90)
##sam.forward(20)
##sam.left(90)
##sam.forward(50)
##sam.left(90)
##sam.forward(20)
##sam.right(90)
##sam.forward(50)
##sam.right(90)
##sam.forward(20)
##sam.left(90)
##sam.forward(50)
##sam.left(90)
##sam.forward(20)
##sam.right(90)
##sam.forward(50)
##sam.right(90)
##sam.forward(20)
##sam.left(90)
##sam.forward(50)
##sam.left(90)
##sam.forward(20)
##sam.right(90)
##sam.forward(50)
##sam.right(90)
##sam.forward(20)
##sam.left(90)
##sam.forward(50)
##sam.left(90)
##sam.forward(20)
##sam.right(90)
##sam.forward(50)
##sam.right(90)
##sam.forward(20)
##sam.left(90)
##sam.forward(50)
##sam.left(90)
##sam.forward(20)
##sam.right(90)
##sam.forward(50)
##sam.right(90)
##sam.forward(20)
##sam.left(90)
##
##
##tom.color('red')
##
##tom.left(60)
##tom.forward(50)
##tom.right(120)
##tom.forward(50)
##tom.left(120)
##
##tom.forward(50)
##tom.right(120)
##tom.forward(50)
##tom.left(120)
##tom.forward(50)
##tom.right(120)
##tom.forward(50)
##tom.left(120)
##tom.forward(50)
##tom.right(120)
##tom.forward(50)
##tom.left(120)
##tom.forward(50)
##tom.right(120)
##tom.forward(50)
##tom.left(120)


